# Generated by Django 5.0.1 on 2026-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('SOCIAL', 'Social'), ('SPORTS', 'Sports & Fitness'), ('STUDY', 'Study Group'), ('FOOD', 'Food & Dining'), ('ENTERTAINMENT', 'Entertainment'), ('CULTURAL', 'Cultural'), ('WELLNESS', 'Wellness'), ('OTHER', 'Other')], default='SOCIAL', max_length=20, verbose_name='category')),
                ('location', models.CharField(max_length=300, verbose_name='location')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True, verbose_name='maximum attendees')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for event categorization', verbose_name='tags')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='is cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event comment',
                'verbose_name_plural': 'event comments',
                'ordering': ['created_at'],
            },
        ),
    ]
