# Generated by Django 5.0.1 on 2026-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('MAINTENANCE', 'Maintenance'), ('EVENT', 'Event'), ('UPDATE', 'Update'), ('ALERT', 'Alert')], default='ANNOUNCEMENT', max_length=20, verbose_name='category')),
                ('accommodation_provider', models.CharField(blank=True, help_text='Leave blank for all providers', max_length=200, verbose_name='accommodation provider')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is pinned')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'news post',
                'verbose_name_plural': 'news posts',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
