# Generated by Django 5.0.1 on 2026-02-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['-published_at'], name='news_newspo_publish_c86f78_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['accommodation_provider'], name='news_newspo_accommo_0f3361_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['category'], name='news_newspo_categor_9982a1_idx'),
        ),
    ]
